<?php

$LABEL = array (
"LANG" => "en",
/* menu */
GANTI_PASS_MENU => "Change Password",
LOGOUT_MENU => "Logout", 
/* master data */
PARAMETER_SISTEM_MENU => "System Parameters",
NEGARA_MENU => "Country", NEGARA_HDR => "Country Forms",
KOTA_MENU => "City", KOTA_HDR => "City Forms",
BANDAR_UDARA_MENU => "Airport", BANDAR_UDARA_HDR => "Airport Forms",
DATA_PENERBANGAN_MENU => "Flight Number", DATA_PENERBANGAN_HDR => "Flight Number Forms",
MATA_UANG_MENU => "Currency", MATA_UANG_HDR => "Currency Forms",
TARIF_DAN_BIAYA_MENU => "Rates", TARIF_DAN_BIAYA_HDR => "Rates Forms",
BIAYA_TAMBAHAN_MENU => "Other Charges", BIAYA_TAMBAHAN_HDR => "Other Charges Forms",
KOMODITI_MENU => "Comodity", KOMODITI_HDR => "Comodity Forms",
JENIS_SETORAN_MENU => "Deposit Types", JENIS_SETORAN_HDR => "Deposit Types Forms",
DATA_PELANGGAN_MENU => "Agent List", DATA_PELANGGAN_HDR => "Agent List Forms", 
/*transaksi*/
SETORAN_PELANGGAN_MENU => "Deposit Agent", SETORAN_PELANGGAN_HDR => "Deposit Agent Forms",
SURAT_MUATAN_UDARA_MENU => "Airways Bill", SURAT_MUATAN_UDARA_HDR => "Airways Bill Forms",
GENERATE_INVOICE_MENU => "Invoicing", GENERATE_INVOICE_HDR => "Invoicing Forms", 
/*report*/
MANIFEST_PENERBANGAN_MENU => "Cargo Manifest", MANIFEST_PENERBANGAN_HDR => "Cargo Manifest Forms", 
SALDO_PELANGGAN_MENU => "Agent Balance", SALDO_PELANGGAN_HDR => "Agent Balance Forms", 
RINCIAN_PENJUALAN_SMU_MENU => "Detail Of Sales", RINCIAN_PENJUALAN_SMU_HDR => "Detail Of Sales Transaction Forms", 
REKAP_PEMAKAIAN_SMU_MENU => "Summary Airways Bill", REKAP_PEMAKAIAN_SMU_HDR => "Summary Airways Bill Transaction Forms", 
REKAP_PENJUALAN_DETAIL_MENU => "Detail Of Airways Bill", REKAP_PENJUALAN_DETAIL_HDR => "Detail Of Airways Bill Transaction Forms", 
REKAP_PENJUALAN_SUMMARY_MENU => "Summary Of Airways Bill", REKAP_PENJUALAN_SUMMARY_HDR => "Summary Of Airways Bill Transaction Forms", 
INVOICE_REPORT_MENU => "Invoice",INVOICE_REPORT_HDR => "Invoice Forms", 

/* form */
/*common label*/
KODE_NEGARA => "Country Code",
NAMA_NEGARA => "Country Name",
KODE_KOTA => "City Code",
NAMA_KOTA => "City Name",
PROPINSI => "Province / States",
KODE_BANDARA => "Airport Code",
NAMA_BANDARA => "Airport Name",
KODE_PENERBANGAN => "Flight Number",
TANGGAL_PENERBANGAN => "Flight Date",
NEGARA_ASAL => "From (Country)",
KOTA_ASAL => "From (City)",
NEGARA_TUJUAN => "Destination (Country)",
JAM_ETD => "ETD",
JAM_ETA => "ETA",
KOTA_TUJUAN => "Destination (City)",
NEGARA_TRANSIT => "Transit (Country)",
KOTA_TRANSIT => "Transit (City)",
KUOTA_KG => "Quotes (KG)",
KUOTA_KOLI => "Quotes (COLI)",
KODE_MATA_UANG => "Currency Code",
NAMA_MATA_UANG => "Currency Name",
KODE_TARIF => "Rate Code",
HARGA_BAHAN_BAKAR => "Fuel Charges",
HARGA_DASAR_KG => "Default Rate (KG)",
HARGA_DASAR_KOLI => "Default Rate (COLI)",
HARGA_RANGE_1_KG => "Rates Range 1 (KG)",
HARGA_RANGE_2_KG => "Rates Range 2 (KG)",
HARGA_RANGE_3_KG => "Rates Range 3 (KG)",
HARGA_RANGE_1_KOLI => "Rates Range 1 (COLI)",
HARGA_RANGE_2_KOLI => "Rates Range 2 (COLI)",
HARGA_RANGE_3_KOLI => "Rates Range 3 (COLI)",
BIAYA_ADMIN_SMU => "Airways Bill Admin",
BIAYA_TAMBAHAN_LAIN => "Other Charges",
PPN => "VAT (Value Added Tax)",
KODE_KOMODITI => "Code Of Comodity",
NAMA_KOMODITI => "Name Of Comodity",
KOMODITI => "Comodity",
KODE_SETORAN => "Deposit Code",
NAMA_SETORAN => "Deposit Type",
KODE_AGENT => "Agent Code",
NAMA_AGENT => "Agent Name",
ALAMAT => "Address",
NEGARA => "Country",
KOTA => "City",
KODE_POS => "ZIP/Postal Code",
TELEPON => "Telephone",
FAXIMILI => "Faximile",
EMAIL => "Email",
WEBSITE => "Website",
NAMA_KONTAK => "Contact Person",
JENIS_TARIF => "Type Of Rate",
/* trans */
NO_SETORAN => "Deposit Code",
TGL_SETORAN => "Deposit Date",
NO_MUATAN => "Airways Bill Code",
TGL_MUATAN => "Airways Bill Date",
SALDO_AGENT => "Agent Balance",
JUMLAH_BARANG => "Number Of Goods",
SISA_KUOTA_KG => "Quota Remaining (KG)",
SISA_KUOTA_KOLI => "Quota Remaining (KOLI)",
NO_INVOICE => "Invoice No",
TGL_INVOICE => "Invoice Date",
JUMLAH_SMU => "Number Of Airways Bill",
TOTAL_INVOICE => "Amount",
/* report */
RPT_TANGGAL => "Date", 
RPT_AGENT => "Agent Name",
RPT_NO_SMU => "Airways Bill Code",
RPT_FLIGHT_NO => "Flight Number",
RPT_FROM => "From",
RPT_DESTINATION => "Destination",
RPT_TARIF_KG => "Rate (KG)",
RPT_TOTAL_KG => "Total (KG)",
RPT_TOTAL_KOLI => "Total (KOLI)",
RPT_AS_AGREED => "As Agreed",
RPT_PPN => "VAT",
RPT_ADM => "Admin",
RPT_TOTAL_TARIF => "Amount",
RPT_KOMODITI => "Comodity",
RPT_JML_CARGO => "Qty Of Cargo",
RPT_KODE_PENERBANGAN => "Flight Number",
RPT_TANGGAL_PENERBANGAN => "Flight Date",
RPT_DEPOSIT => "Deposit",
RPT_SALDO => "Balance",

/*general label*/
JUMLAH_DATA => "Record Count",
HALAMAN => "Pages",
SIMPAN => "Save",
BATAL => "Cancel",
PROSES_INVOICE => "Process Invoices",
TAMPILKAN_DATA => "View Data",
EXPORT_EXCEL => "Export To Excel",
CETAK => "Print",
PRINT_BARCODE => "Print Barcode",
QTY => "Qty",
HARGA => "Rate",
JUMLAH => "Amount",
MATA_UANG => "Currency",
KETERANGAN => "Description",
TOTAL => "Total",
TANGGAL_AWAL => "Start Date",
TANGGAL_AKHIR => "End Date",
BULAN => "Month",
TAHUN => "Year",
/*alert*/
DATA_TDK_DIKETEMUKAN => "Data not found.",
PESAN_KONFIRMASI_LOGOUT => "Are you sure want to logout?.",


/*setup*/
"LANG_ID" => "0"
);



?>